main: me.cynadyde.barrelsplus.BarrelsPlusPlugin
name: BarrelsPlus
version: "1.15.2-2"
api-version: "1.14"
description: >
  Barrels keep their inventory when broken! However, they
  they still drop any non-empty containers nested inside.
  Barrels also cannot be used as fuel in a furnace.
website: https://www.spigotmc.org/resources/barrelsplus.67224/
authors:
  - Cynadyde (May 2019)
